[package]
name = "tiered-result"
authors = ["person93 <person93.person93@gmail.com>"]
version = "0.1.0-dev"
edition = "2021"
description = "A different approach to error handling"
license = "MIT"

[dependencies]
nullable-result = { version = "0.7.0", features = ["try_trait"] }
